interface LanguageTranslations {
    it: string
}

const Translations = new Map<string, LanguageTranslations>([
    ["Add new style:", {it: "Aggiungi nuovo stile:"}],
    ["Style name:", {it: "Nome dello stile:"}],
    ["Style type:", {it: "Tipo dello stile:"}],
    ["Paragraph", {it: "Paragrafo"}],
    ["Character", {it: "Carattere"}],
    ["List", {it: "Lista"}],
    ["Table", {it: "Tabella"}],
    ["Show this style as a quick style in Word's \"Styles\" tab", {it: "Mostra questo stile come stile rapido nella sezione \"Stili\" di Word"}],
    ["Inside border", {it: "Bordo interno"}],
    ["Outside border", {it: "Bordo esterno"}],
    ["Color", {it: "Colore"}],
    ["Type", {it: "Tipo"}],
    ["Width", {it: "Larghezza"}],
    ["Specific border options", {it: "Opzioni specifiche dei bordi"}],
    ["Inside border", {it: "Bordo interno"}],
    ["Outside border", {it: "Bordo esterno"}],
    ["Top border", {it: "Bordo in alto"}],
    ["Bottom border", {it: "Bordo in basso"}],
    ["Left border", {it: "Bordo a sinistra"}],
    ["Right border", {it: "Bordo a destra"}],
    ["InsideHorizontal border", {it: "Bordo interno orizzontale"}],
    ["InsideVertical border", {it: "Bordo interno verticale"}],
    ["All borders", {it: "Tutti i bordi"}],
    ["Border width", {it: "Larghezza del bordo"}],
    ["Border type", {it: "Tipo del bordo"}],
    ["Discard the changes made to this property", {it: "Elimina le modifiche fatte a questa proprietà"}],
    ["Bold", {it: "Grassetto"}],
    ["Italic", {it: "Corsivo"}],
    ["Strikethrough", {it: "Barrato"}],
    ["Double Strikethrough", {it: "Doppio barrato"}],
    ["Superscript", {it: "Apice"}],
    ["Subscript", {it: "Pedice"}],
    ["Underline", {it: "Sottolineato"}],
    ["Size (in points)", {it: "Dimensione (in punti)"}],
    ["Font name", {it: "Nome del font"}],
    ["Highlight color", {it: "Colore dell'evidenziatore"}],
    ["Table cell spacing", {it: "Spazio delle celle in una tabella"}],
    ["You can choose how much empty space there should be around each cell.", {it: "Puoi scegliere quanto spazio vuoto ci dovrebbe essere attorno ad ogni cella."}],
    ["Value unit", {it: "Unità del valore"}],
    ["points", {it: "punti"}],
    ["Paragraph indent", {it: "Indentazione del paragrafo"}],
    ["By changing the paragraph indent value, you can put some empty space before the first line. You can both put a positive value (image 1) or a negative value (image 2)", {it: "Cambiando il valore dell'indentazione del paragrafo, puoi mettere un po' di spazio vuoto prima dell'inizio della prima linea. Puoi mettere sia un valore positivo (immagine 1) o un valore negativo (immagine 2)"}],
    ["List number format", {it: "Formato dei numeri della lista:"}],
    ["You can change how the numbers or bullet points should be displayed, by adding some text before or after them. In the image example, the", {it: "Puoi cambiare come i numeri o i punti dovrebbero essere mostrati, aggiungendo del testo prima o dopo di essi. Nell'esempio,"}],
    ["text has been added after the number", {it: "è stato aggiunto dopo il numero"}],
    ["Second line position", {it: "Posizione della seconda linea:"}],
    ["With this property, you can change the space before the start of every line after the first one. For example, in the first image this property was set to a normal value, while in the second one was set to", {it: "Con questa proprietà, puoi cambiare lo spaizo prima dell'inizio di ogni linea dopo la prima. Ad esempio, nella prima immagine questa proprietà è stata impostata ad un valore normale, mentre nella seconda è stato impostato su"}],
    ["Table with some empty space around each cell", {it: "Tabella con dello spazio vuoto attorno ad ogni cella"}],
    ["Paragraph with indent positive applied: the text of the first line starts after if compared to the text of the other lines", {it: "Pagrafo con indentazione positiva applicata: il testo della prima liena parte dopo rispetto al testo delle altre linee"}],
    ["Paragraph with indent negative applied: the text of the first line starts before the text of the other lines", {it: "Paragrafo con indentazione negativa applicata: il testo della prima liena inizia prima rispetto al testo delle altre linee"}],
    ["Custom number format", {it: "Formato del numero personalizzato"}],
    ["Normal second line position property", {it: "Posizione della seconda linea impostata su un valore normale"}],
    ["Second line position set to 40: the text of the second and third line is positioned more at the right than the first line", {it: "Posizione della seconda linea impostata su 40: il testo della seconda e terza linea è posizionato più a destra rispetto alla prima linea"}],
    ["Keep paragraph on the same line", {it: "Mantieni paragrafo sulla stessa linea"}],
    ["As the title says, if this option is enabled, the paragraph will be put in the same page as the paragraph which follows it. Note that, in the video, the last two lines of the Lorem ipsum have been made a new line", {it: "Come dice il titolo, se quest'opzione è abilitata, il paragrafo viene messo nella stessa pagina del paragrafo che lo segue. Nota che, nel video, le ultime due linee del Lorem ipsum sono state messe come nuova linea"}],
    ["Keep paragraph on the same page", {it: "Mantieni paragrafo sulla stessa pagina:"}],
    ["If enabled, all the lines of the paragraph will be kept in the same page. So, if at least one line should go in a new page, all the paragraph will be put in the new page", {it: "Se abilitato, tutte le linee del paragrafo verranno mantenute sulla stessa pagina. Quindi, se almeno una liena dovesse andare in una nuova pagina, tutto il paragrafo sarebbe messo nella nuova pagina."}],
    ["Shading options", {it: "Opzioni di shading"}],
    ["With shading options, you can customize the background color of the paragraph. Here you can see an example, done by mixing red and yellow and by setting the shading type to", {it: "Con le opzioni di shading, puoi personalizzare il colore di sfondo. Qui puoi vedere un esempio, creato mischiando il rosso ed il giallo e impostando il tipo dell'ombreggiatura su"}],
    ["Custom shading", {it: "Shading personalizzato"}],
    ["Level outline", {it: "Livello del testo"}],
    ["The level the paragraph should be displayed if a summary is generated, from 1 to 9. If it shouldn't be displayed,", {it: "Il livello del paragrafo utilizzato nei sommari/indici, da 1 a 9. Nel caso non dovesse comparire, usare"}],
    [" should be selected", {it: ""}],
    ["Tab position", {it: "Posizione della tabulazione"}],
    ["Choose how much tabulation space should be added between the number/bullet point and the first character of the list. If you haven't set it, you might see a really high value. This is normal, but know that usually setting it of a few tens of points is more than enough (since setting it to a high value, like thousands of points, will cause Word to reject the style change)", {it: "Scegli quanto spazio dovrebbe esserci tra il numero/punto ed il primo caratterre della lista. Se non lo hai personalizzato, potresti vedere un valore molto alto. Questo è normale, ma tieni a mente che impostarlo su un valore basso (come qualche decina) è sufficiente (visto che, se impostato ad un valore alto, come migliaia di punti, potrebbe impedire il salvataggio dello stile)"}],
    ["Close", {it: "Chiudi"}],
    ["First item on a list, with a lot of spcae between the number and the first character", {it: "Primo elemento della lista, con molto spazio tra il numero ed il primo carattere"}],
    ["Is an ordered (numeric) list", {it: "È una lista ordinata (numerica)"}],
    ["Position number", {it: "Posizione numero"}],
    ["Alignment", {it: "Allineamento"}],
    ["Unknown", {it: "Sconosciuto"}],
    ["Left", {it: "Sinistra"}],
    ["Centered", {it: "Centrato"}],
    ["Right", {it: "Destra"}],
    ["Justified", {it: "Giustificato"}],
    ["An item of list level", {it: "Un elemento della lista di livello"}],
    ["should appear before restarting counting from 1", {it: "dovrebbe apparire prima di riniziare il conteggio da 1"}],
    ["Blank spaces", {it: "Spazi vuoti"}],
    ["Blank space (in points) at the left of the list", {it: "Spazio vuoto (in punti) a sinistra della lista"}],
    ["Position (in points) of the second line of text", {it: "Posizione (in punti) della seconda linea di testo"}],
    ["After the number/symbol, add a:", {it: "Dopo il numero/simbolo, aggiungi uno/a:"}],
    ["tabulation", {it: "tabulazione"}],
    ["space", {it: "spazio"}],
    ["nothing", {it: "niente"}],
    ["Number-specific list options", {it: "Opzioni specifiche degli elenchi numerici"}],
    ["Number format", {it: "Formato del numero"}],
    ["Number style", {it: "Stile del numero,"}],
    ["Starting number of the list", {it: "Numero iniziale della lista"}],
    ["Font options (probably won't work)", {it: "Opzioni del font (probabilmente non funzionerà)"}],
    ["Next paragraph style", {it: "Stile del prossimo paragrafo"}],
    ["Make this style a quick style", {it: "Imposta questo stile come stile rapido"}],
    ["Make this style visible in the \"Recommended style\" tab", {it: "Imposta questo stile come visibile nella sezione degli \"Stili suggeriti\""}],
    ["Make this style visible in the \"Recommended style\" tab after it has been used", {it: "Imposta questo stile come visible nella sezione degli \"Stili suggeriti\" dopo che è stato usato"}],
    ["Priority", {it: "Priorità"}],
    ["Base style", {it: "Stile base"}],
    ["Indent (in points)", {it: "Indentazione (in punti)"}],
    ["Keep all the lines of the paragraph in the same page", {it: "Mantieni tutte le linee del paragrafo sulla stessa pagina"}],
    ["Put this paragraph in the same page as the next paragraph", {it: "Metti questo paragrafo nella stessa pagina del prossimo paragrafo"}],
    ["Avoid sending the second or last line to a new page (the first or second-last line will be moved too)", {it: "Evita di mandare la seconda o l'ultima linea in una nuova pagina (anche la prima o la penultima linea sarà spostata)"}],
    ["Level", {it: "Livello"}],
    ["Indentation", {it: "Indentazione"}],
    ["Left", {it: "Sinistra"}],
    ["Right", {it: "Destra"}],
    ["Spacing", {it: "Spaziatura"}],
    ["Line spacing", {it: "Spaziatura di ogni linea"}],
    ["Space before the paragraph", {it: "Spazio prima del paragrafo"}],
    ["Space after the paragraph", {it: "Spazio dopo del paragrafo"}],
    ["Foreground color", {it: "Colore principale"}],
    ["Background color", {it: "Colore dello sfondo"}],
    ["Texture type", {it: "Tipo della texture"}],
    ["The lines can be broken across pages", {it: "Le linee possono essere spezzate tra le pagine"}],
    ["Cell spacing", {it: "Spazio della cella"}],
    ["Cell margin", {it: "Margine della cella"}],
    ["Change Word styles using the Office.JS API", {it: "Cambia gli stili di Word utilizzando le API di Office.JS"}],
    ["Change styles", {it: "Cambia stili"}],
    ["Change the styles of your document, and create new ones.", {it: "Cambia gli stili del tuo documento, e creane di nuovi."}],
    ["Load styles", {it: "Carica stili"}],
    ["Apply style", {it: "Applica stile"}],
    ["Apply a style to the text you've selected on Word", {it: "Applica uno stile al testo che hai selezionato su Word"}],
    ["Change selection", {it: "Cambia selezione"}],
    ["Change how the selected text looks, without creating a new style", {it: "Cambia come viene mostrato il testo, senza creare un nuovo stile"}],
    ["Get selection", {it: "Ottieni selezione"}],
    ["Export styles", {it: "Esporta stili"}],
    ["You'll be able to choose which styles to export in a JSON file", {it: "Potrai scegliere quali stili esportare in un file JSON"}],
    ["Import styles", {it: "Importa stili"}],
    ["If you've exported a JSON file before, you can import its styles here", {it: "Se hai già esportato un file JSON, puoi importare i suoi stili qui"}],
    ["If a style with the same name is found", {it: "Se uno stile con lo stesso nome viene trovato"}],
    ["overwrite it", {it: "Sovrascrivilo"}],
    ["ignore it", {it: "Ignoralo"}],
    ["keep both of them", {it: "Mantienili entrambi"}],
    ["Pick JSON file", {it: "Scegli il file JSON"}],
    ["Font", {it: "Font"}],
    ["Paragraph", {it: "Paragrafo"}],
    ["Border", {it: "Bordo"}],
    ["Shading (background color)", {it: "Shading (colore di sfondo)"}],
    ["List order", {it: "Ordine della lista"}],
    ["General options", {it: "Opzioni generali"}],
    ["Font options", {it: "Opzioni del font"}],
    ["Paragraph options", {it: "Opzioni dei paragrafi"}],
    ["Border options", {it: "Opzioni dei bordi"}],
    ["General options", {it: "Opzioni generali"}],
    ["Shading options", {it: "Opzioni di shading"}],
    ["Table options", {it: "Opzioni della tabella"}],
    ["List options", {it: "Opzioni della lista"}],
    ["Save", {it: "Salva"}],
    ["Discard edits", {it: "Scarta modifiche"}],
    ["Apply this style", {it: "Applica questo stile"}],
    ["Apply", {it: "Applica"}],
    ["Apply changes", {it: "Applica modifiche"}],
    ["Pick the properties you want to export. To avoid freezes when importing, choose only the properties you've changed.", {it: "Seleziona le proprietà che vuoi esportare. Per evitare dei blocchi durante l'importazione, seleziona solo le proprietà che hai cambiato."}],
    ["Export", {it: "Esporta"}],
    ["Toggle all checkboxes", {it: "Alterna la selezione"}],
    ["Do you want to go back to the home?", {it: "Vuoi tornare alla home?"}],
    ["You'll lose all the unsaved changes.", {it: "Perderai tutte le modifiche non salvate."}],
    ["Yes", {it: "Sì"}],
    ["No", {it: "No"}],
    ["Download file", {it: "Scarica file"}],
    ["Unfortunately, the platform you're using doesn't support file downloading. Copy the link displayed below, and then open it in your browser. Don't worry, your ultra-personal styles will always be private, and they aren't uploaded anywhere (all the download process happens locally).", {it: "Sfortunatamente, la piattaforma che stai usando non supporta il download dei file. Copia il link mostrato qui sotto, ed aprilo nel tuo browser. Non preoccuparti i tuoi stili rimarranno sempre privati, e non sono stati caricati da nessuna parte (tutto il processo del download avviene localmente)."}],
    ["Copy", {it: "Copia"}],
    ["View open source licenses", {it: "Visualizza licenze open source"}],
    ["Change theme", {it: "Cambia tema"}],
    ["Open source licenses", {it: "Licenze open source"}],
    ["Select one of the following open source libraries to see its license", {it: "Seleziona una delle librerie open source usate per vedere la sua licenza"}],
    ["An error occurred", {it: "Si è verificato un errore"}],
    ["Here you can change the selected lists. Note that you need to save the settings in this section every time you edit a level, not at the end with the \"Apply edits\" button outside this card.", {it: "Qui puoi cambiare le liste selezionate. Nota che devi salvare queste impostazioni manualmente ogni volta che hai modificato un livello, e non col pulsante \"Applica modifiche\" fuori da questa card."}],
    ["Edit level", {it: "Modifica livello"}],
    ["Don't change", {it: "Non cambiarlo"}],
    ["Change bullet type", {it: "Cambia il tipo di punto"}],
    ["Bullet type", {it: "Tipo di punto"}],
    ["Custom character", {it: "Carattere personalizzato"}],
    ["Font of the custom character", {it: "Font del carattere personalizzato"}],
    ["Change indentation", {it: "Cambia indentazione"}],
    ["Text indentation", {it: "Indentazione del testo"}],
    ["Space left at the left of the bullet point", {it: "Spazio lasciato a sinistra del punto elenco"}],
    ["Change number type", {it: "Cambia la tipologia di numero"}],
    ["Number type", {it: "Tipo di numero"}],
    ["Use an image for the current bullet point", {it: "Utilizza un'immagine per il punto elenco corrente"}],
    ["Change the starting number of the list", {it: "Cambia il numero d'inizio della lista"}],
    ["Start from", {it: "Inizia da"}],
    ["Lists", {it: "Liste"}],
    ["You can reference the values of the current level by writing", {it: "Puoi far riferimento ai valori del livello corrente scrivendo"}],
    ["You can reference previous levels by writing the dollar sign followed by the list level, and then another dollar sign", {it: "Puoi far riferimento a valori di livelli precedenti scrivendo il segno del dollaro, seguito dal livello della lista e da un altro segno del dollaro"}],
    ["If you need to use the dollar sign everywhere else, write", {it: "Se devi usare il segno del dollaro da qualsiasi altra parte, scrivi"}],
    ["(without the closing dollar sign!)", {it: "(senza il simbolo del dollaro alla fine!)"}],
    ["Write here the number format. Note that:", {it: "Scrivi qui il formato del numero. Nota che:"}],
    ["Change the number format", {it: "Cambia il formato del numero"}],
    ["Word and Office are trademarks of Microsoft. This project is no way affiliated or endorsed by Microsoft", {it: "Word e Office sono marchi di Microsoft. Questo progetto non è in alcun modo affiliato o sponsorizzato da Microsoft"}],
    ["GIF where the second last paragraph goes to the new page with the last paragraph", {it: "GIF dove il penultimo paragrafo viene spostato in una nuova pagina con l'ultimo paragrafo"}],
    ["GIF where the entire paragraph goes to a new page", {it: "GIF dove l'intero paragrafo viene spostato in una nuova pagina"}],
    ["Store these settings so that they'll be restored the next time you'll open the add-in", {it: "Salva queste impostazioni in modo da ripristinarle la prossima volta che aprirai l'add-in"}],
    ["Custom shape", {it: "Forma personalizzata"}],
    ["Shape type", {it: "Tipo della forma"}],
    ["Width (in points):", {it: "Larghezza (in punti):"}],
    ["Height (in points):", {it: "Altezza (in punti):"}],
    ["Border radius, from 0 (square) to 0.5 (circle):", {it: "Raggio del bordo, da 0 (quadrato) a 0.5 (cerchio):"}],
    ["Fill", {it: "Riempimento"}],
    ["Single color", {it: "Colore singolo"}],
    ["Gradient", {it: "Sfumatura"}],
    ["Image", {it: "Immagine"}],
    ["Select the color", {it: "Seleziona il colore"}],
    ["Gradient angle", {it: "Angolo della sfumatura"}],
    ["Add colors", {it: "Aggiungi colori"}],
    ["Color", {it: "Colore"}],
    ["Position of this color (between 0 and 1)", {it: "Posizione di questo colore (tra 0 e 1)"}],
    ["Add a PNG instead of a JPEG", {it: "Aggiungi un PNG al posto di un JPEG"}],
    ["Output image quality (for JPEG)", {it: "Qualità dell'immagine di destinazione (per il JPEG)"}],
    ["Keep aspect ratio by resizing", {it: "Mantieni l'aspect ratio ridimensionando"}],
    ["the height", {it: "l'altezza"}],
    ["the width", {it: "la larghezza"}],
    ["none of the above", {it: "nessuna delle precedenti"}],
    ["Pick image", {it: "Scegli immagine"}],
    ["Copy from clipboard", {it: "Copia dagli appunti"}],
    ["Add shape", {it: "Aggiungi forma"}],
    ["Transparency", {it: "Trasparenza"}],
    ["Advanced border settings", {it: "Impostazioni avanzate sul bordo"}],
    ["Line type", {it: "Tipo di linea"}],
    ["Single", {it: "Singola"}],
    ["Double", {it: "Doppia"}],
    ["Double (thick and thin)", {it: "Doppia (spessa e sottile)"}],
    ["Double (thin and tick)", {it: "Doppia (sottile e spessa)"}],
    ["Triple", {it: "Tripla"}],
    ["Line style", {it: "Stile della linea"}],
    ["Normal", {it: "Normale"}],
    ["Dotted", {it: "Punteggiato"}],
    ["Dashed", {it: "Tratteggiato"}],
    ["Long dashes", {it: "Tratteggiato lungo"}],
    ["Dashes with dots", {it: "Trattini con punti"}],
    ["Really long dashes", {it: "Tratteggiato molto lungo"}],
    ["Really long dashes with dots", {it: "Tratteggiato molto lungo con puntini"}],
    ["Really long dashes with double dots", {it: "Tratteggiato molto lungo con puntini doppi"}],
    ["Border color:", {it: "Colore del bordo:"}],
    ["None", {it: "Nessuno"}],
    ["Plain color", {it: "Colore semplice"}],
    ["Linear gradient", {it: "Sfumatura lineare"}],
    ["Border size (in points)", {it: "Dimensione del bordo (in punti)"}],
    ["Select an image", {it: "Seleziona un'immagine"}],
    ["Selected image", {it: "Immagine selezionata"}],
    ["transparency", {it: "trasparenza"}],
    ["position", {it: "posizione"}],
    ["Customize shapes", {it: "Personalizza forme"}],
    ["Create a new shape with a custom border radius, background color (both plain and gradient) or background image", {it: "Crea una nuova forma con un raggio del bordo personalizzato e con un colore (sia normale che con sfumatura) od un'immagine come sfondo"}],
    ["Create new shape", {it: "Crea nuova forma"}],
    ["Table alignment", {it: "Allineamento della tabella"}],
    ["Vertical alignment", {it: "Allineamento verticale"}],
    ["all cells", {it: "tutte le celle"}],
    ["Horizontal alignment", {it: "Allineamento orizzontale"}],
    ["Cell-specific styling", {it: "Stile della singola cella"}],
    ["Since you might want to edit different cells, you'll need to click on the \"Update\" button inside each card to apply the settings to only the selected cell", {it: "Visto che potresti voler modificare differenti celle, dovrai cliccare sul tasto \"Aggiorna\" dentro ogni riquadro per applicare le impostazioni sulla singola cella"}],
    ["Cell of row", {it: "Cella di riga"}],
    ["and column", {it: "e colonna"}],
    ["Edit", {it: "Modifica"}],
    ["Update border", {it: "Aggiorna bordo"}],
    ["Cell padding", {it: "Spazio vuoto attorno alla cella"}],
    ["Update the following paddings", {it: "Aggiorna i seguenti spazi vuoti"}],
    ["Padding width (in points)", {it: "Larghezza dello spazio vuoto (in punti)"}],
    ["Update padding", {it: "Aggiorna spazio vuoto"}],
    ["Other single cell styles", {it: "Altri stili della singola cella"}],
    ["single cell", {it: "cella singola"}],
    ["Cell color", {it: "Colore della cella"}],
    ["Update cell styling", {it: "Aggiorna stile della cella"}],
    ["Top", {it: "Alto"}],
    ["Center", {it: "Centro"}],
    ["Bottom", {it: "Basso"}],
    ["Edit the following border", {it: "Modifica il bordo seguente"}],
    ["All", {it: "Tutti"}],
    ["Inside", {it: "Dentro"}],
    ["Outside", {it: "Fuori"}],
    ["Inside Horizontal", {it: "Dentro Orizzontale"}],
    ["Inside Vertical", {it: "Dentro Verticale"}],
    ["Allow shape overlapping", {it: "Permetti la sovrapposizione di forme"}],
    ["Shape position", {it: "Posizione della forma"}],
    ["Text frame settings", {it: "Impostazioni del contenitore del testo"}],
    ["Orientation", {it: "Orientamento"}],
    ["Standard", {it: "Standard"}],
    ["Horizontal", {it: "Orizzontale"}],
    ["Horizontal (East-Asian) (Rotated)", {it: "Orizzontale (Asia dell'Est) (Ruotato)"}],
    ["Vertical (East-Asian)", {it: "Verticale (Asia dell'Est)"}],
    ["Vertical", {it: "Verticale"}],
    ["Vertical (270°)", {it: "Verticale (270°)"}],
    ["Text alignment", {it: "Allineamento del testo"}],
    ["Enable word wrapping", {it: "Manda a capo automaticamente"}],
    ["Disable text rotation when rotating the shape", {it: "Disabilita la rotazione del testo quando si ruota la forma"}],
    ["Margin", {it: "Margine"}],
    ["Top margin", {it: "Margine in alto"}],
    ["Bottom margin", {it: "Margine in basso"}],
    ["Left margin", {it: "Margine a sinistra"}],
    ["Right margin", {it: "Margine a destra"}],
    ["Geometric shape type", {it: "Tipo della forma geometrica"}],
    ["Shapes", {it: "Forme"}],
    ["Select all the cells in the selected row", {it: "Seleziona tutte le celle nella riga selezionata"}],
    ["Select all the cells in the selected column", {it: "Seleziona tutte le celle nella colonna selezionata"}],
    ["Add hyperlink", {it: "Aggiungi collegamento"}],
    ["Refresh list", {it: "Aggiorna lista"}],
    ["Top of the page", {it: "In alto alla pagina"}],
    ["Other", {it: "Altro"}],
    ["Headings", {it: "Titoli"}],
    ["Bookmarks", {it: "Segnalibri"}],
    ["Choose either a bookmark or a heading. The link will be added to all the selected text", {it: "Scegli tra un segnalibro oppure un'intestazione. Il collegamento verrà aggiunto a tutto il testo evidenziato"}],
    ["Update link", {it: "Aggiorna collegamento"}],
    ["Add bookmark", {it: "Aggiungi segnalibro"}],
    ["Bookmark name", {it: "Nome del segnalibro"}],
    ["Create bookmark", {it: "Crea segnalibro"}],
    ["Add a bookmark, or link the selected text to an already-existing bookmark", {it: "Aggiungi un segnalibro, oppure collega il testo selezionato ad un segnalibro già esistente"}],
    ["Add field", {it: "Aggiungi campo"}],
    ["Flags", {it: "Personalizzazioni"}],
    ["Variable type", {it: "Tipo della variabile"}],
    ["Add a dynamic variable in your document", {it: "Aggiungi una variabile dinamica nel tuo documento"}],
    ["Add field", {it: "Aggiungi campo"}],
    ["Axis", {it: "Assi"}],
    ["Edit the following axis", {it: "Modifica l'asse seguente"}],
    ["Series", {it: "Serie"}],
    ["Category", {it: "Categorie"}],
    ["Value", {it: "Valori"}],
    ["On Excel, there are two main chart axis types: the \"Value\" one, that usually is the one on the y axis, and the \"Category\" one, that usually is the one on the x axis. On 3D graphs, there might be also another axis (the \"Series\" axis), but in most cases you don't need to touch it.", {it: "Su Excel, ci sono due tipologie di assi del grafico: l'asse dei \"Valori\", che solitamente è quello dell'asse y, e l'asse delle \"Categorie\", che solitamente è quello sull'asse x. Nei grafici 3D, potrebbe esserci anche un altro asse (l'asse \"Serie\"), ma nella maggioranza dei casi non c'è bisogno di modificarlo."}],
    ["Axis types", {it: "Tipologie di assi"}],
    ["Styling", {it: "Stile"}],
    ["Height (in points)", {it: "Altezza (in punti)"}],
    ["Distance from left", {it: "Distanza da sinistra"}],
    ["Chart range", {it: "Gamma di valori del grafico"}],
    ["Minimum", {it: "Minimo"}],
    ["Maximum", {it: "Massimo"}],
    ["Number format", {it: "Formato dei numeri"}],
    ["Major ticks", {it: "Trattini grandi"}],
    ["Tick mark", {it: "Tipologia di trattino"}],
    ["Cross", {it: "Croce"}],
    ["Interval between tick marks", {it: "Intervallo tra trattini"}],
    ["Minor ticks", {it: "Trattini piccoli"}],
    ["Ticks", {it: "Trattini"}],
    ["Show unit label", {it: "Mostra la casella con l'unità"}],
    ["Tick mark label rotation", {it: "Rotazione del testo associato ai trattini"}],
    ["Position of tick label", {it: "Posizione della casella di testo associata ai trattini"}],
    ["Spacing between tick marks", {it: "Spaziatura tra trattini"}],
    ["Add a label every (this) categories/values", {it: "Aggiungi una casella ogni (questo) categorie/valori"}],
    ["Advanced", {it: "Avanzato"}],
    ["Axis category type", {it: "Tipologia di categoria dell'asse"}],
    ["Next to the axis", {it: "Di fianco all'asse"}],
    ["High", {it: "Alto"}],
    ["Low", {it: "Basso"}],
    ["Automatic", {it: "Automatico"}],
    ["Text", {it: "Testo"}],
    ["Date", {it: "Data"}],
    ["Base time unit", {it: "Unità del tempo di base"}],
    ["Days", {it: "Giorni"}],
    ["Months", {it: "Mesi"}],
    ["Years", {it: "Anni"}],
    ["Display unit", {it: "Unità visualizzata"}],
    ["Scale type", {it: "Tipologia di scala"}],
    ["Linear", {it: "Lineare"}],
    ["Logarithmic", {it: "Logaritmica"}],
    ["Logarithmic base", {it: "Base del logaritmo"}],
    ["Data labels", {it: "Caselle dei dati"}],
    ["Data label", {it: "Casella dei dati"}],
    ["Automatically generate the text inside the label", {it: "Genera automaticamente il testo all'interno della casella"}],
    ["Shape type", {it: "Tipologia della forma"}],
    ["Separator string", {it: "Stringa separatrice"}],
    ["Position", {it: "Posizione"}],
    ["Text rotation", {it: "Rotazione del testo"}],
    ["Text position", {it: "Posizione del testo"}],
    ["Number format", {it: "Formato dei numeri"}],
    ["Link the number format to the one used in the axis", {it: "Mantieni lo stesso formato dei numeri utilizzato nell'asse"}],
    ["Custom number format", {it: "Formato numerico personalizzato"}],
    ["Show bubble size", {it: "Mostra la dimensione della bolla"}],
    ["Show category name", {it: "Mostra il nome della categoria"}],
    ["Show legend key", {it: "Mostra l'identificatore della legenda"}],
    ["Show percentage", {it: "Mostra la percentuale"}],
    ["Show series name", {it: "Mostra il nome della serie"}],
    ["Show value", {it: "Mostra valore"}],
    ["Some charts display different things. Pick the ones that apply to your chart.", {it: "Alcuni grafici mostrano cose differenti. Scegli quelle che sono corrispondenti al tuo grafico."}],
    ["Chart data", {it: "Dati del grafico"}],
    ["Rounded corners", {it: "Bordi arrotondati"}],
    ["Apply", {it: "Applica"}],
    ["Legend", {it: "Legenda"}],
    ["Single legend entry", {it: "Singolo elemento della legenda"}],
    ["Edit legend number", {it: "Modifica legenda numero"}],
    ["Make it visible", {it: "Rendila visibile"}],
    ["General settings", {it: "Impostazioni generali"}],
    ["Legend height", {it: "Altezza della legenda"}],
    ["Overlap the legend with the main chart", {it: "Sovrapponi la legenda con il grafico principale"}],
    ["Show a shadow in the legend background", {it: "Mostra un'ombra nello sfondo della legenda"}],
    ["Make the legend visible", {it: "Rendi la legenda visibile"}],
    ["Corner", {it: "Bordo"}],
    ["Custom", {it: "Personalizzato"}],
    ["Legend position", {it: "Posizione della legenda"}],
    ["Weight", {it: "Spessore"}],
    ["Style", {it: "Stile"}],
    ["Color", {it: "Colore"}],
    ["Foreground color", {it: "Colore principale"}],
    ["Background color", {it: "Colore di sfondo"}],
    ["Size", {it: "Dimensione"}],
    ["Chart area", {it: "Area del grafico"}],
    ["Chart area border", {it: "Bordo dell'area del grafico"}],
    ["Plot position in the chart", {it: "Posizione del grafico principale nell'area"}],
    ["Edit inside properties", {it: "Modifica le proprietà interiori"}],
    ["Series", {it: "Serie"}],
    ["Edit series number", {it: "Modifica la serie numero"}],
    ["Histogram interval options", {it: "Opzioni dell'intervallo degli istogrammi"}],
    ["Allow overflow", {it: "Permetti la sovrapposizione"}],
    ["Overflow value", {it: "Valore della sovrapposizione"}],
    ["Allow underflow", {it: "Permetti sottopposizione"}],
    ["Underflow value", {it: "Valore edlla sottoposizione"}],
    ["Boxwhisker chart options", {it: "Opzioni del diagramma a scatola e baffi"}],
    ["Quartile calculation", {it: "Indice di posizione"}],
    ["Inclusive", {it: "Inclusivo"}],
    ["Exclusive", {it: "Esclusivo"}],
    ["Show inner points", {it: "Mostra i punti interni"}],
    ["Show mean line", {it: "Mostra la linea mediana"}],
    ["Show mean marker", {it: "Mostra il punto della mediana"}],
    ["Show outlier points", {it: "Mostra i punti anomali"}],
    ["Bubble chart options", {it: "Impostazioni della bolla"}],
    ["Bubble size (scaling in percentage)", {it: "Dimensione della bolla (scalato in percentuale)"}],
    ["Chart-type specific options", {it: "Impostazioni specifiche della tipologia del grafico"}],
    ["Doughnut hole size", {it: "Dimensione del buco del grafico a ciambella"}],
    ["Explosion", {it: "Esplosione"}],
    ["Angle of the first slice", {it: "Angolo della prima fetta"}],
    ["Gap width", {it: "Larghezza della distanza"}],
    ["Overlap", {it: "Sovrapposizione"}],
    ["Region map specific settings", {it: "Impostazioni specifiche della mappa"}],
    ["Gradient styling", {it: "Stile della sfumatura"}],
    ["Two phase group", {it: "Gruppo a due fasi"}],
    ["Three phase group", {it: "Gruppo a tre fasi"}],
    ["Region levels", {it: "Livello delle regioni"}],
    ["Edit gradient options of the", {it: "Modifica le impostazioni della sfumatura del"}],
    ["Midpoint", {it: "Mezzo"}],
    ["Extreme value", {it: "Valore estremo"}],
    ["Number", {it: "Numero"}],
    ["Percentage", {it: "Percentuale"}],
    ["Maximum value", {it: "Valore massimo"}],
    ["Treemap-specific chart settings", {it: "Impostazioni del grafico ad albero"}],
    ["Parent label position", {it: "Posizione della casella superiore"}],
    ["Waterfall-specific chart settings", {it: "Impostazioni specifiche del grafico a cascata"}],
    ["Show connector lines", {it: "Mostra le linee di connessione"}],
    ["Display settings", {it: "Impostazioni di display"}],
    ["Name", {it: "Nome"}],
    ["Add a shadow effect", {it: "Aggiungi un effetto ombra"}],
    ["Each item in the series should have a different color", {it: "Ogni elemento nella serie dovrebbe avere un colore differente"}],
    ["Negative points", {it: "Punti negativi"}],
    ["Color for negative data points", {it: "Colore per i punti negativi"}],
    ["Invert the pattern if negative", {it: "Inverti il pattern se negativo"}],
    ["Marker settings", {it: "Impostazioni dei punti"}],
    ["Single point settings", {it: "Impostazioni di ogni singolo punto"}],
    [`Note that you need to manually apply these settings with the "Apply" button of this card, and not with the one on the bottom of the page. You can change these settings for all the markers from the "Display settings" card above`, {it: "Nota che dovrai applicare manualmente queste impotazioni con il pulsante \"Applica\" di questa card, e non con quella alla fine di questa pagina. Puoi cambiare queste impostazione per ogni puntino dalla card \"Impostazioni di display\" in alto"}],
    ["Edit point number", {it: "Elimina punto numero"}],
    ["Marker", {it: "Punto"}],
    ["Border of the legend square", {it: "Bordo del quadrato della legenda"}],
    ["Show data label", {it: "Mostra casella dei dati"}],
    ["Filtered chart", {it: "Grafico filtrato"}],
    ["Add a label with the data", {it: "Aggiungi una casella col dato"}],
    ["Plot order", {it: "Ordine del grafico"}],
    ["Show leader lines", {it: "Mostra una linea che connette la legenda col punto"}],
    ["Make the series smooth", {it: "Rendi la serie smooth"}],
    ["Format", {it: "Formato"}],
    ["Second chart size", {it: "Dimensione del secondo grafico"}],
    ["How the two sections should be split", {it: "Come le due sezioni dovrebbero essere divise"}],
    ["Position", {it: "Posizione"}],
    ["Value", {it: "Valore"}],
    ["Percent value", {it: "Valore della percentuale"}],
    ["Custom split", {it: "Divisione personalizzata"}],
    ["Treshold value for splitting the two sections", {it: "Valore che separa le due sezioni"}],
    ["Chart title", {it: "Titolo del grafico"}],
    ["Other settings", {it: "Altre impostazioni"}],
    ["Add a shadow behind the title", {it: "Aggiungi un'ombra dietro al titolo"}],
    ["Permit the title to overlay the chart", {it: "Permetti al titolo di sovrapporsi al grafico"}],
    ["Make the title visible", {it: "Rendi il titolo visibile"}],
    ["Border type", {it: "Tipo del bordo"}],
    ["Is visible", {it: "È visibile"}],
    ["Other chart properties", {it: "Altre proprietà del grafico"}],
    ["Chart type", {it: "Tipo del grafico"}],
    ["Display blank cells as", {it: "Mostra celle vuote come"}],
    ["Use for data", {it: "Utilizza come dati"}],
    ["Rows", {it: "Righe"}],
    ["Columns", {it: "Colonne"}],
    ["Plot only visible cells", {it: "Considera solo le celle visibili"}],
    ["Show data labels even if their value is over the maximum displayed in the axis", {it: "Mostra la casella coi dati anche se il suo valore è sopra il massimo visualizzato nell'asse"}],
    ["Axis options", {it: "Opzioni dell'asse"}],
    ["Format options", {it: "Opzioni del formato"}],
    ["Legend options", {it: "Opzioni della legenda"}],
    ["Chart area options", {it: "Opzioni dell'area del grafico"}],
    ["Series options", {it: "Opzioni delle serie"}],
    ["Data labels options", {it: "Opzioni delle caselle coi dati"}],
    ["Title options", {it: "Opzioni del titolo"}],
    ["Other chart options", {it: "Altre opzioni del grafico"}],
    ["Edit chart", {it: "Modifica grafico"}],
    ["A list of all the available charts will appear. Pick the one you want to edit from the dropdown menu", {it: "Una lista di tutti i grafici disponibili apparirà. Scegli quello che vuoi modificare dal menù a tendina"}],
    ["Pick the chart to edit", {it: "Scegli il grafico da modificare"}],
    ["Export a chart as an image", {it: "Esporta il grafico come immagine"}],
    ["Pick a chart, choose its witdh/height, and save it as a PNG image", {it: "Seleziona un grafico, scegli la sua larghezza/altezza, e salvalo come immagine PNG"}],
    ["Pick chart", {it: "Scegli grafico"}],
    ["Pick the chart to edit", {it: "Scegli il grafico da modificare"}],
    ["Export chart image", {it: "Esporta immagine del grafico"}],
    ["Fitting mode", {it: "Modalità di riempimento"}],
    ["Fit", {it: "Adatta"}],
    ["Fit and center", {it: "Adatta e riempi"}],
    ["Fill", {it: "Riempi"}],
    ["Export", {it: "Esporta"}],
    ["Hidden properties", {it: "Proprietà nascoste"}],
    ["Since the element you're editing hasn't been added yet, you can't edit some of its properties. After you've added it, go back to the home by clicking on the extension logo on the top of the page to access them", {it: "Visto che l'elemento che stai modificando non è ancora stato aggiunto, non puoi modificare alcune delle sue proprietà. Dopo averlo aggiunto, torna alla home premento il logo dell'icona in alto alla pagina per poterle modificare"}],
    ["Justify", {it: "Giustificato"}],
    ["Distributed", {it: "Distribuito"}],
    ["Add label every", {it: "Aggiungi casella ogni"}],
    ["entries", {it: "valori"}],
    ["You can choose to show the label of that axis every x entries. For example, in the image below this property was set to 2 in the \"Category\" axis", {it: "Puoi scegliere di mostrare la casella di testo di quell'asse ogni x valori. Ad esempio, nell'immagine in basso questa proprietà è stata impostata su 2 nell'asse delle categorie"}],
    ["Chart where the bottom axis label is shown every two items", {it: "Grafico dove la casella di testo dell'asse in basso è mostrata ogni due elementi"}],
    ["Axis label rotation", {it: "Rotazione della casella dell'asse"}],
    ["You can change the rotation of the axis labels. In this example, it was set to \"25\". Also negative values are accepted.", {it: "Puoi cambiare la rotazione della casella di testo dell'asse. In quest'esempio, è stata impostata su \"25\". Sono accettati anche valori negativi."}],
    ["Chart where the bottom axis label is slightly rotated", {it: "Grafico dove la casella dell'asse in basso è leggermente ruotata"}],
    ["Legend shadow", {it: "Ombra della legenda"}],
    ["A shadow effect is added to the legend rectangle.", {it: "Viene aggiunto un effetto ombra al rettangolo."}],
    ["Legend with a shadow effect", {it: "Legenda con un effetto ombra"}],
    ["Data labels are the labels before each point, that show its value.", {it: "Le caselle dei dati sono le caselle prima di ogni punto, che mostrano il suo valore."}],
    ["Title shadow", {it: "Ombra del titolo"}],
    ["Add a shadow to the title border.", {it: "Aggiungi un'ombra al titolo del bordo."}],
    ["The space that is left between each series. If the number is high, more space will be left. In the first image, this value is set to \"200\", while in the second it's set to \"100\".", {it: "Lo spazio che viene lasciato tra ogni serie. Se il numero è alto, verrà lasciato più spazio. Nella prima immagine, questo valore è impostato su \"200\", mentre nella seconda è impostato su \"100\"."}],
    ["More space between the columns (high number)", {it: "Più spazio tra le colonne (numero alto)"}],
    ["Less space between the columns (low number)", {it: "Meno spazio tra le colonne (numero basso)"}],
    ["Chart angle", {it: "Angolo del grafico"}],
    ["Change the angle where the chart starts. In the first image, the pie starts normally, while in the second it starts at 45°", {it: "Cambia l'angolo dove il grafico comincia. Nella prima immagine, la torta inizia normalmente, mentre nella seconda inizia a 45°"}],
    ["Chart explosion", {it: "Esplosione del grafico"}],
    ["Add more space in the center of the chart. In the first image, the \"Explosion\" property is set to 0, while in the second one to 15", {it: "Aggiungi più spazio al centro del grafico. Nella prima immagine, la proprietà \"Esplosione\" è impostata su 0, mentre nella seconda su 15"}],
    ["Customize content control", {it: "Modifica i controlli"}],
    ["Permissions", {it: "Permessi"}],
    ["Cannot delete", {it: "Non si può eliminare"}],
    ["Cannot edit", {it: "Non si può modificare"}],
    ["Item list", {it: "Lista degli elementi"}],
    ["Add new item", {it: "Aggiungi nuovo elemento"}],
    ["Displayed text", {it: "Testo visualizzato"}],
    ["Value", {it: "Valore"}],
    ["Index (negative value to put it in last position)", {it: "Indice (valore negativo per metterlo nell'ultima posizione)" }],
    ["Add item to list", {it: "Aggiungi elemento alla lista"}],
    ["Edit single item", {it: "Modifica singolo elemento"}],
    ["Edit item in position", {it: "Modifica elemento nella posizione"}],
    ["Title", {it: "Titolo"}],
    ["Index", {it: "Indice"}],
    ["Delete entry", {it: "Elimina elemento"}],
    ["Change properties", {it: "Cambia proprietà"}],
    ["Other settings", {it: "Altre impostazioni"}],
    ["Tag", {it: "Tag"}],
    ["Add content control", {it: "Aggiungi controllo"}],
    ["Add comboboxes, checkboxes etc. on your Word document. You can customize them with the \"Customize Content Control\" card below", {it: "Aggiungi caselle di controllo, menù a tendina etc. nel tuo documento di Word. Puoi personalizzarli con la card \"Personalizza controlli\" in basso."}],
    ["Add", {it: "Aggiungi"}],
    ["Customize content control", {it: "Personalizza controlli"}],
    ["Change some properties of the content control", {it: "Cambia alcune proprietà dei controlli"}],
    ["Get selected content controls", {it: "Ottieni i controlli selezionati"}],
    ["While refreshing, get also titles from the table of content. Disable if you're facing issues.", {it: "Quando viene aggiornata la lista, ottieni anche i titoli dall'indice. Disabilita se stai avendo problemi."}]
])

let isOfficeReady = false;
export const updateOfficeReady = () => (isOfficeReady = true);

/**
 * Get the translation of a string
 * @param str the string to translate
 * @returns the translated string
 */
export function lang(str: string) {
    if (!isOfficeReady) return str;
    const temp = Translations.get(str);
    if (temp) return temp[Office.context.displayLanguage.substring(0, 2) as "it"] ?? str;
    return str;
}